language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: app-devopslab-helloworld
  api_key:
    secure: I3tbmFq1M1ZHJqYSZ0p1kij+gmvnkCPk7AksA2nC1ycYV7m90pBZuOqffeHeQgRgJOjsWy0VhlIC+G5vKvnRLN8aL3FPsWzAMQvdLOSF86fARs+im9onY2yuRiTXA7tSNnLwm5wmGQZ1+zwe/osFVaibydaCFnfgGC6OvWeXoiItWP4tjwnQ4FXX0271DuY4ZVHyKfyCxmAW37O8JizsSNfnjVKDiobQK6a/bPEdn6Y7mWgqWHgsk63ci5n+VNQUtKmMzFe8p3N19UfySrIPXgfW8PK/1gRBuAhXl3g8J3oUywoagF97QhEimg2xEiH98WpFfz01Vt4de+v1LYKUw0OiST7iAmmxzeOnbtuBm+OiWhZt8SA0rJjZJvg126rJ+3iMQLflh3j//IHAvAZBAaGw/bb7rq5Dyse7VmwI9SS+NOiYJPmoXujYCJ4wgmglZbJJk3zR5yoBQvRQHJK3rMVi+sjJQHwhQ1uJ43kHGlIWkD51ubwcQW1VT4RjojmeZMypfD88q8H4wnV7iG6BtNI3eFTmNejsYU89W5WOvQmo6fONAt7tvckjQ1O99tfBBRbbcVB/1b9n9AYTmDMTIQk/WKoOdmQaNHqHBZSOPSUZWCOpAP6NweMNau+I2d6/7nsVGEtF9D4karkgkusKKngNQAIYQFdn9Dsvq91OsRI=
